{{- if .Values.hsmocsp.enabled }}
{{- range .Values.hsmocsp.extraSecrets }}
apiVersion: v1
kind: Secret
metadata: {{- tpl .metadata $ | trim | nindent 2 }}
{{ with .type }}
type: {{- tpl . $ | trim | nindent 2 }}
{{- end }}
{{ with .data }}
data: {{- tpl . $ | trim | nindent 2 }}
{{- end }}
---
{{- end }}
{{- end }}