{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "app-hsmocsp.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "app-hsmocsp.labels" . | nindent 4 }}
{{- end -}}
{{- if .Values.hsmocsp.enabled }}
{{- range .Values.hsmocsp.extraServiceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata: {{- tpl .metadata $ | trim | nindent 2 }}
{{- end }}
{{- range .Values.hsmocsp.extraRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata: {{- tpl .metadata $ | trim | nindent 2 }}
rules:  {{- tpl .rules $ | trim | nindent 2 }}
{{- end }}
{{- range .Values.hsmocsp.extraClusterRoles }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata: {{- tpl .metadata $ | trim | nindent 2 }}
{{ with .aggregationRule }}
aggregationRule: {{- tpl . $ | trim | nindent 2 }}
{{- end }}
rules:  {{- tpl .rules $ | trim | nindent 2 }}
{{- end }}
{{- range .Values.hsmocsp.extraRoleBindings }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata: {{- tpl .metadata $ | trim | nindent 2 }}
roleRef:  {{- tpl .roleRef $ | trim | nindent 2 }}
subjects: {{- tpl .subjects $ | trim | nindent 2 }}
{{- end }}
{{- range .Values.hsmocsp.extraClusterRoleBindings }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata: {{- tpl .metadata $ | trim | nindent 2 }}
roleRef:  {{- tpl .roleRef $ | trim | nindent 2 }}
subjects: {{- tpl .subjects $ | trim | nindent 2 }}
{{- end }}
{{- end }}
