apiVersion: v1
kind: Service
metadata:
  name: app-hsmocsp
  namespace: default
  labels:
    app.kubernetes.io/name: app-hsmocsp
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: app-hsmocsp
  