apiVersion: v1
kind: Service
metadata:
  name: app-hsmocsp
  namespace: default
  labels:
    app.kubernetes.io/name: app-hsmocsp
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
  type: ClusterIP