---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-hsmocsp
  namespace: default
  labels:
    app.kubernetes.io/name: app-hsmocsp
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
 name: app-hsmocsp-edit-binding
 namespace: default
 labels:
    app.kubernetes.io/name: app-hsmocsp
subjects:
- kind: ServiceAccount
  name: app-hsmocsp
  namespace: default
roleRef:
 kind: ClusterRole
 name: edit
 apiGroup: rbac.authorization.k8s.io