---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: default
  labels:
    app.kubernetes.io/name: app-hsmocsp
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: role-tokenreview-binding
  namespace: default
  labels:
    app.kubernetes.io/name: app-hsmocsp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-auth
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-auth-secret
  namespace: default
  labels:
    app.kubernetes.io/name: app-hsmocsp
  annotations:
    kubernetes.io/service-account.name: vault-auth
type: kubernetes.io/service-account-token