---
server:
  logLevel: 0
  host: 127.0.0.1
  port: 8080
  timeout:
    server: 30
    read: 15
    write: 10
    idle: 5
  readinessProbeHandle:
    pattern: 'readyz'
  livenessProbeHandle:
    pattern: 'healthz'
  opensslSourceHandles:
    - ca:
        hostFiles: true
        certPattern: 'ca'
        certPath: '.config/ca/ca.cert.pem'
        crlPattern: 'crl'
        crlPath: '.config/ca/crl/ca.crl.pem'
        indexPath: '.config/ca/certindex'
      ocsp:
        pattern: 'ocsp'
        certPath: '.config/ca/ocsp.cert.pem'
        keyPath: ''
        keyHsm:
          modulePath: '/usr/lib/softhsm/libsofthsm2.so'
          slotNumber: -1
          tokenLabel: 'pki-hsm'
          keyLabel: 'ocsp-keypair'
          keyID: ''
          pin: ''
  vaultSourceHandles:
    - vault:
        pkiMount: 'pki'
        api:
            address: 'http://127.0.0.1:8200'
            agentAddress: '127.0.0.1:8007'
      ocsp:
        pattern: 'pki/ocsp'
        certPath: '.config/ca/ocsp.pki.cert.pem'
        keyPath: ''
        keyHsm:
          modulePath: '/usr/lib/softhsm/libsofthsm2.so'
          slotNumber: -1
          tokenLabel: 'pki-hsm'
          keyLabel: 'ocsp-keypair'
          keyID: ''
          pin: ''
    - vault:
        pkiMount: 'pki_int_development'
        api:
            address: 'http://127.0.0.1:8200'
            agentAddress: '127.0.0.1:8007'
      ocsp:
        pattern: 'pki_int_development/ocsp'
        certPath: '.config/ca/ocsp.pki_int_development.cert.pem'
        keyPath: ''
        keyHsm:
          modulePath: '/usr/lib/softhsm/libsofthsm2.so'
          slotNumber: -1
          tokenLabel: 'pki-hsm'
          keyLabel: 'ocsp-keypair'
          keyID: ''
          pin: ''